"""empty message

Revision ID: bb029cdbaf08
Revises: 
Create Date: 2025-05-04 15:22:22.474461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb029cdbaf08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sender_id'), ['sender_id'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(name) <= 30'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.UnicodeText(), nullable=False),
    sa.Column('email', sa.UnicodeText(), nullable=False),
    sa.Column('contact_email', sa.UnicodeText(), nullable=True),
    sa.Column('password_hash', sa.UnicodeText(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('permission', sa.Integer(), nullable=False),
    sa.Column('viewer', sa.Integer(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('otp_secret', sa.UnicodeText(), nullable=True),
    sa.Column('admin_token', sa.Integer(), nullable=True),
    sa.Column('about_me', sa.UnicodeText(), nullable=True),
    sa.Column('photo', sa.UnicodeText(), nullable=True),
    sa.Column('song', sa.UnicodeText(), nullable=True),
    sa.Column('language', sa.UnicodeText(), nullable=False),
    sa.Column('location', sa.UnicodeText(), nullable=True),
    sa.Column('phone', sa.UnicodeText(), nullable=True),
    sa.Column('label', sa.UnicodeText(), nullable=True),
    sa.Column('banner_flag', sa.UnicodeText(), nullable=True),
    sa.Column('token', sa.UnicodeText(), nullable=True),
    sa.Column('editor', sa.UnicodeText(), nullable=True),
    sa.Column('utc_offset', sa.Float(), nullable=False),
    sa.Column('birth', sa.DateTime(), nullable=True),
    sa.Column('joined', sa.DateTime(), nullable=False),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('last_notification_read_time', sa.DateTime(), nullable=False),
    sa.Column('last_feed_read_time', sa.DateTime(), nullable=False),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(about_me) <= 500'),
    sa.CheckConstraint('char_length(banner_flag) <= 8'),
    sa.CheckConstraint('char_length(contact_email) <= 320'),
    sa.CheckConstraint('char_length(email) <= 320'),
    sa.CheckConstraint('char_length(label) <= 32'),
    sa.CheckConstraint('char_length(language) <= 16'),
    sa.CheckConstraint('char_length(location) <= 200'),
    sa.CheckConstraint('char_length(phone) <= 64'),
    sa.CheckConstraint('char_length(photo) <= 200'),
    sa.CheckConstraint('char_length(song) <= 300'),
    sa.CheckConstraint('char_length(token) <= 32'),
    sa.CheckConstraint('char_length(username) <= 64'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.UnicodeText(), nullable=False),
    sa.Column('body_html', sa.UnicodeText(), nullable=False),
    sa.Column('language', sa.UnicodeText(), nullable=False),
    sa.Column('direct', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('ghost', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('utc_offset', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(body) <= 5000'),
    sa.CheckConstraint('char_length(language) <= 16'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_votes'), ['votes'], unique=False)

    op.create_table('flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('utc_offset', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flag_user_id'), ['user_id'], unique=False)

    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('language', sa.UnicodeText(), nullable=False),
    sa.Column('photos', sa.LargeBinary(), nullable=True),
    sa.Column('utc_offset', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(language) <= 16'),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.UnicodeText(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.UnicodeText(), nullable=False),
    sa.Column('language', sa.UnicodeText(), nullable=False),
    sa.Column('utc_offset', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(item_type) <= 32'),
    sa.CheckConstraint('char_length(language) <= 16'),
    sa.CheckConstraint('char_length(name) <= 100'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=False),
    sa.Column('body', sa.UnicodeText(), nullable=False),
    sa.Column('body_html', sa.UnicodeText(), nullable=False),
    sa.Column('language', sa.UnicodeText(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('pin_comments', sa.Integer(), nullable=False),
    sa.Column('removed_comments', sa.Integer(), nullable=False),
    sa.Column('direct_comments', sa.Integer(), nullable=False),
    sa.Column('disable_comments', sa.Boolean(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('label', sa.UnicodeText(), nullable=True),
    sa.Column('viewer', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('photos', sa.UnicodeText(), nullable=True),
    sa.Column('editor', sa.UnicodeText(), nullable=True),
    sa.Column('utc_offset', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('edit_timestamp', sa.DateTime(), nullable=True),
    sa.CheckConstraint('char_length(body) <= 20000'),
    sa.CheckConstraint('char_length(label) <= 30'),
    sa.CheckConstraint('char_length(language) <= 16'),
    sa.CheckConstraint('char_length(title) <= 3000'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments'), ['comments'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_utc_offset'), ['utc_offset'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_votes'), ['votes'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.CheckConstraint('char_length(description) <= 200'),
    sa.CheckConstraint('char_length(id) <= 64'),
    sa.CheckConstraint('char_length(name) <= 100'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('utc_offset', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_user_id'), ['user_id'], unique=False)

    op.create_table('tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_vote_post_id'))

    op.drop_table('vote')
    op.drop_table('task')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_votes'))
        batch_op.drop_index(batch_op.f('ix_post_utc_offset'))
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_index(batch_op.f('ix_post_language'))
        batch_op.drop_index(batch_op.f('ix_post_comments'))

    op.drop_table('post')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notification_name'))
        batch_op.drop_index(batch_op.f('ix_notification_item_type'))

    op.drop_table('notification')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))

    op.drop_table('message')
    op.drop_table('follows')
    with op.batch_alter_table('flag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flag_user_id'))

    op.drop_table('flag')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_votes'))
        batch_op.drop_index(batch_op.f('ix_comment_timestamp'))

    op.drop_table('comment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('tag')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sender_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_message_id'))

    op.drop_table('conversation')
    # ### end Alembic commands ###
